version: '3.8'

services:
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frk_fed
      MYSQL_USER: user_frk
      MYSQL_PASSWORD: root_frk
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  fed-service:
    build:
      context: ./FED_Service
      dockerfile: Dockerfile
    container_name: fed-service
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: frk_fed
      DB_USERNAME: user_frk
      DB_PASSWORD: root_frk
    ports:
      - "8002:80"

  frk-service:
    build:
      context: ./FRK_Service
      dockerfile: Dockerfile
    container_name: frk-service
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: frk_fed
      DB_USERNAME: user_frk
      DB_PASSWORD: root_frk
    ports:
      - "8003:80"

  frk-fed-auth-service:
    build:
      context: ./FRK-FED-Authentication-Service
      dockerfile: Dockerfile
    container_name: frk-fed-auth-service
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: frk_fed
      DB_USERNAME: user_frk
      DB_PASSWORD: root_frk
    ports:
      - "8004:80"

  laravel-frontend:
    build:
      context: ./FrontEnd-FRK
      dockerfile: Dockerfile
    container_name: laravel-frontend
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: frk_fed
      DB_USERNAME: user_frk
      DB_PASSWORD: root_frk
    ports:
      - "8080:80"

volumes:
  mysql-data:
